<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yar</string>
	</array>
	<key>name</key>
	<string>Yara</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>/\*\*|\{\s*$</string>
			<key>name</key>
			<string>foldingStartMarker</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*/|^\s*\}</string>
			<key>name</key>
			<string>foldingStopMarker</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.yara</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.yara</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.yara</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.yara</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&gt;\\\s*\n)</string>
			<key>name</key>
			<string>punctuation.separator.continuation.yara</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(all|and|any|ascii|at|condition|contains|entrypoint|false|filesize|fullword|for|global|in|import|include|int8|int16|int32|int8be|int16be|int32be|matches|meta|nocase|not|or|of|private|rule|strings|them|true|uint8|uint16|uint32|uint8be|uint16be|uint32be|wide)\b</string>
			<key>name</key>
			<string>keyword.yara</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(0(x|X)[0-9a-fA-F]+)(MB|KB)?\b</string>
			<key>name</key>
			<string>constant.numeric.yara</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$|#|@)[a-zA-Z0-9_*]*</string>
			<key>name</key>
			<string>variable.other.yara</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.yara</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.yara</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.yara</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.yara</string>
				</dict>
			</dict>
			<key>end</key>
			<string>/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.yara</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.regexp.yara</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.yar</string>
	<key>uuid</key>
	<string>60a8246e-250d-4563-8807-f34e82031301</string>
</dict>
</plist>
